### DISCUSSION TITLE
Working on Synology?

### DISCUSSION THREAD

**Discussion by Delgrey** [aceberg/WatchYourLAN#176] [General]
Has anyone ever got this running in Synology Container Manager? I've tried multiple times but for the life of me I can't get it to show any data. Any hints would be appreciated.

**Comment by cthonney** [comment]
Hello,
it's working for me.
my docker compose.

```
version: "3"
services:
  wyl:
    image: aceberg/watchyourlan
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    network_mode: "host"
    restart: unless-stopped
    volumes:
    - /volume2/docker/wyl/data:/data/WatchYourLAN
    environment:
      TZ: Indian/Mauritius
      IFACES: ovs_eth0
      PORT: 8840
      THEME: grass
      COLOR: dark
```
