### ISSUE TITLE
ERROR exit status 1

### ISSUE THREAD

**Issue by RmigD** [aceberg/WatchYourLAN#188]
I am getting an error right after I run the container.

```
 ✔ Container wyl  Recreated                                                                                                                         0.1s 
Attaching to wyl
wyl  | 2025/05/02 22:06:15 INFO ARP_STRS_JOINED: 
wyl  | 2025/05/02 22:06:15 INFO Log level=INFO
wyl  | 2025/05/02 22:06:15 INFO Using DB type=sqlite
wyl  | 2025/05/02 22:06:15 INFO Config dir path=/data/WatchYourLAN
wyl  | 2025/05/02 22:06:15 INFO =================================== 
wyl  | 2025/05/02 22:06:15 INFO Web GUI at http://0.0.0.0:8840
wyl  | 2025/05/02 22:06:15 INFO =================================== 
wyl  | 2025/05/02 22:06:15 INFO Removing all History before date="2025-04-30 22:06:15"
wyl  | 2025/05/02 22:06:15 INFO Removed records from History n=0
wyl  | 2025/05/02 22:06:15 ERROR exit status 1
```
```

services:
    watchyourlan:
        image: aceberg/watchyourlan
        volumes:
            - './data:/data/WatchYourLAN'
        cap_add:
            - NET_RAW
            - NET_ADMIN
        networks:
            host: {}
        environment:
            - TZ=Europe/Lisbon
            - IFACES=eno1
        container_name: wyl
networks:
    host: {}

```
