### ISSUE TITLE
Design not showing

### ISSUE THREAD

**Issue by BangerTech** [aceberg/WatchYourLAN#57]
Hey there, 
first of all thanks for the great project. 
i´m running into an issue and i can´t get my head around ;-)
using the local docker-compose file but i only see this web-ui:
what am i doing wrong? 
```
version: "3"
services:
  node-bootstrap:
    image: aceberg/node-bootstrap:latest
    restart: unless-stopped
    ports:
    - 8850:8850
  wyl:
    image: aceberg/watchyourlan:latest
    network_mode: "host"      
    restart: unless-stopped
    command: "-n http://127.0.0.1:8850"
    depends_on:
      - node-bootstrap
    volumes:
    - ./data:/data
    environment:
      TZ: Europe/Berlin              # required: needs your TZ for correct time
      IFACE: "ens18"                   # required: 1 or more interface
      DBPATH: "/data/db.sqlite"         # optional, default: /data/db.sqlite
      GUIIP: "0.0.0.0"                  # optional, default: localhost
      GUIPORT: "8840"                   # optional, default: 8840
      TIMEOUT: "120"                    # optional, time in seconds, default: 60
      SHOUTRRR_URL: ""                  # optional, set url to notify
      THEME: "darkly"                   # optional
      IGNOREIP: "no"                    # optional
```

<img width="1216" alt="Screenshot 2023-08-07 at 19 33 41" src="https://github.com/aceberg/WatchYourLAN/assets/73241309/91d7d326-109e-4d43-a429-c5d0c7e761c7">
