### ISSUE TITLE
Web gui not working

### ISSUE THREAD

**Issue by bun-dev** [aceberg/WatchYourLAN#90]
Hello, I'm trying to run the docker version but I cannot access the web ui from http://localhost:8840. Everything looks fine in the container logs, so I'm not sure what the issue is. 

docker-compose.yml
```
version: "3.6"
name: watchyourlan
services:
  wyl:
    image: aceberg/watchyourlan:latest
    container_name: watchlan
    network_mode: "host"      
    restart: unless-stopped
    volumes:
    - '/path/to/my/watchyourlan/data:/data'
```
---
config.yaml
```
color: "dark"
dbpath: '/data/db.sqlite'
guiip: "0.0.0.0"
guiport: "8840"
iface: "enp2s0"
ignoreip: "no"
loglevel: "verbose"
theme: "darkly"
timeout: 120
tz: "America/New_York"
shoutrrr_url: "https://gotify.com/message?token=******/?title=Unknown host detected&DisableTLS=yes"
auth: true
auth_expire: "60d"
auth_user: "******"
auth_password: "$$******"
```
Here are the container logs. It's definitely working and scanning my local network. 
![ss 06-30-24](https://github.com/aceberg/WatchYourLAN/assets/34141271/f9971b2f-7869-4024-9bd0-ca52d53f5394)

I also see WatchYourLAN is listening to port 8840
![ss 06-30-24 (1)](https://github.com/aceberg/WatchYourLAN/assets/34141271/c312fee2-470b-425b-8e7e-df4579fef952)
